# Generated by Django 4.2 on 2024-09-03 19:25

import django.contrib.postgres.indexes
import django.core.validators
from django.db import migrations, models
import links.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('link_type', models.CharField(max_length=254)),
                ('link_code', models.CharField(max_length=254, null=True)),
                ('object1', models.UUIDField()),
                ('object2', models.UUIDField()),
                ('weight', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('direction', models.SmallIntegerField(choices=[(0, '00'), (1, '01'), (2, '10'), (3, '11')], default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('meta', models.JSONField(default=links.models.meta_default_value)),
                ('data', models.JSONField(default=dict, null=True)),
                ('project_id', models.UUIDField(default=None, null=True)),
                ('account_id', models.UUIDField(default=None, null=True)),
                ('user_id', models.UUIDField(default=None, null=True)),
            ],
            options={
                'ordering': ['-meta__internal_id'],
            },
        ),
        migrations.AddIndex(
            model_name='link',
            index=django.contrib.postgres.indexes.GinIndex(fields=['data'], name='links_data_gin'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['link_type'], name='links_link_type_idx'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['object1', 'link_type', 'object2'], name='links_obj1_link_type_obj2_idx'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['created_date'], name='links_created_date_idx'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['modified_date'], name='links_modified_date_idx'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['project_id', 'account_id', 'user_id'], name='links_prj_id_acc_id_usr_id_idx'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['account_id', 'user_id'], name='links_account_id_user_id_idx'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['user_id'], name='links_user_id_idx'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['object2', 'object1', 'link_type'], name='links_obj2_obj1_lt_idx'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['object1', 'object2', 'link_type'], name='links_obj1_obj2_lt_idx'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['object2', 'link_type', 'object1'], name='links_obj2_lt_obj1_idx'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['link_code', 'project_id', 'link_type'], name='link_code_proj_type_idx'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['link_code', 'project_id', 'account_id', 'link_type'], name='link_code_proj_acc_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='link',
            constraint=models.CheckConstraint(check=models.Q(('weight__gte', 0.0), ('weight__lte', 1.0)), name='link_weight_range'),
        ),
        migrations.AddConstraint(
            model_name='link',
            constraint=models.CheckConstraint(check=models.Q(('direction__gte', 0), ('direction__lte', 3)), name='link_direction_range'),
        ),
        migrations.AddConstraint(
            model_name='link',
            constraint=models.UniqueConstraint(fields=('link_code', 'project_id', 'link_type'), name='link_code_proj_type'),
        ),
        migrations.AddConstraint(
            model_name='link',
            constraint=models.UniqueConstraint(fields=('link_code', 'project_id', 'account_id', 'link_type'), name='link_code_proj_acc_type'),
        ),
    ]
