# Generated by Django 4.2 on 2024-09-03 19:25

import django.contrib.postgres.indexes
from django.db import migrations, models
import ratings.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('project_id', models.UUIDField(default=None, null=True)),
                ('account_id', models.UUIDField(default=None, null=True)),
                ('user_id', models.UUIDField(default=None, null=True)),
                ('object_type', models.CharField(max_length=254, null=True)),
                ('object_item', models.UUIDField(default=None, null=True)),
                ('object_code', models.CharField(max_length=254, null=True, unique=True)),
                ('name', models.CharField(max_length=254, null=True)),
                ('meta', models.JSONField(default=ratings.models.meta_default_value)),
                ('data', models.JSONField(default=ratings.models.data_default_value, null=True)),
            ],
            options={
                'ordering': ['-meta__internal_id'],
            },
        ),
        migrations.AddIndex(
            model_name='rating',
            index=django.contrib.postgres.indexes.GinIndex(fields=['data'], name='ratings_data_gin'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['object_item'], name='ratings_object_item_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['created_date'], name='ratings_cr_date_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['modified_date'], name='ratings_mod_date_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['object_item', 'object_type'], name='ratings_o_item_type_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['project_id', 'account_id', 'user_id'], name='ratings_p_a_u_ids_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['account_id', 'user_id'], name='ratings_a_u_ids_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['user_id'], name='ratings_user_id_idx'),
        ),
    ]
